### PR TITLE
Some bug-fixes and improvements

### LINKED ISSUE #90: Default log level to Info
Currently the newly opened project console is set to the "trace" log level by default. Is it possible that the default level is "info" as in the Appcelerator Studio?

### LINKED ISSUE #91: iOS: Distinguish certificates and profiles with the same name
I work with many apps, and with many certificate updates and different versions of AdHoc app profiles to which new devices are enabled.

The certificate list shows the different versions of distribution certificates with the same name and can not distinguish between expiration dates. Moreover it happens that by choosing the second certificate it is actually always selected the first one in the list with the same name, and I can not then select the associated distribution profile.

Likewise if I have multiple profiles for the same app it is not possible to understand the version, as only the name is shown and not the UUID code.

### LINKED ISSUE #103: Uncaught TypeError: Cannot read property 'hud' of undefined
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'hud' of undefined

```
At /Users/admin/.atom/packages/appcelerator-titanium/lib/index.js:187

TypeError: Cannot read property 'hud' of undefined
    at /packages/appcelerator-titanium/lib/index.js:187:16
    at Function.module.exports.Emitter.simpleDispatch (/Users/admin/Desktop/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Users/admin/Desktop/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /packages/appcelerator-titanium/lib/project.js:65:21
    at Function.module.exports.Emitter.simpleDispatch (/Users/admin/Desktop/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Users/admin/Desktop/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at didChangeCallback (/Users/admin/Desktop/Atom.app/Contents/Resources/app/src/project.js:381:28)
    at PathWatcher.onNativeEvents (/Users/admin/Desktop/Atom.app/Contents/Resources/app/src/path-watcher.js:533:13)
    at sub.native.onDidChange.events (/Users/admin/Desktop/Atom.app/Contents/Resources/app/src/path-watcher.js:436:64)
    at Function.module.exports.Emitter.simpleDispatch (/Users/admin/Desktop/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Users/admin/Desktop/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NSFWNativeWatcher.onEvents (/Users/admin/Desktop/Atom.app/Contents/Resources/app/src/path-watcher.js:167:24)
    at handler (/Users/admin/Desktop/Atom.app/Contents/Resources/app/src/path-watcher.js:276:18)
```

### Commands

```
     -0:27.5.0 core:cut (input.hidden-input)
     -0:26.1.0 core:backspace (input.hidden-input)
  3x -0:23.6.0 core:save (input.hidden-input)
     -0:01.1.0 editor:move-to-first-character-of-line (input.hidden-input)
```

### Non-Core Packages

```
appcelerator-titanium 1.1.0 
atom-beautify 0.29.24 
build 0.69.0 
busy-signal 1.4.1 
hyperclick 0.1.5 
intentions 1.1.2 
language-babel 2.77.3 
linter 2.0.0 
linter-eslint 8.4.0 
linter-jshint 3.1.2 
linter-ui-default 1.2.4 
pigments 0.39.1 
titanium-alloy 0.14.6 
titanium-build 0.8.1 
```

### LINKED ISSUE #108: Liveview  :improvement:
Live view check or selector. Can you implement a check or selector to add another parameter on run with live view  '--liveview','true'. For now I add this parameters on source code on app.js
.....
let args = {};
		if (buildCommand === 'run') {
			args = [
				'--platform', platform,
				'--target', targetType,
				'--log-level', logLevel,
				'--liveview','true'
			];
.....
thanks

### LINKED ISSUE #114: Autosave custom args
When running with custom arguments, it's usually the way developers run their project each and every time. And every time Atom is being restarted there's a need to re-enter the same arguments.

Have the option (inside the package settings - should be true by default) to auto save the last ran "Custom args" that was were put in the text box and loaded when the custom args appears automatically.

### PR DESCRIPTION
**Pull request by hansemannn**
- Fix #91: Add expiration date to certificates **and** provisioning profiles

bildschirmfoto 2018-07-01 um 09 58 59

- Fix #108: Add LiveView

bildschirmfoto 2018-07-01 um 10 49 10

- Fix #103: Fix HUD-error
- Fix #90: Use `INFO` log-level by default, for parity with Studio
- Fix #114: Allow custom args to be saved across Atom sessions

### CODE REVIEW

File: lib/ui/toolbar.js [hunk 1]
```diff
@@ -237,6 +238,7 @@ export default class Toolbar {
 						</Select>
 
 						<Button icon="gear" flat="true" disabled={this.state.disableUI || !this.state.codeSigningAvailable} click={this.expandButtonClicked.bind(this)} />
+						<Button icon="eye" flat="true" coDisabled={this.state.disableLiveView} disabled={this.state.disableUI || this.state.buildCommand !== 'run'} click={this.liveViewButtonClicked.bind(this)} />
```
Comment (ewanharris) [inline lib/ui/toolbar.js]: I think this button should be available when using custom builds? So maybe `!(this.state.buildCommand === 'run' || this.state.buildCommand === 'custom')`

File: lib/index.js [hunk 2]
```diff
@@ -184,6 +184,8 @@ export default {
 		atom.menu.update();
 
 		Project.onModified(() => {
+			if (!this.toolbar) { return; }
```
Comment (ewanharris) [inline lib/index.js]: Linting prefers only 1 statement per line, we can clean this up in the travis PR though

File: lib/index.js [hunk 3]
```diff
@@ -352,7 +354,8 @@ export default {
 			targetType,
 			iOSCodeSigning,
 			androidKeystore,
-			customArgs
+			customArgs,
+			disableLiveView
```
[the remark this answers is not in the document]
Comment (hansemannn) [reply lib/index.js]: It was primarily selected because of the "disabled" directive of the view, but I agree to change it.
